apiVersion: v1
kind: Pod
metadata:
  name: michael-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: DB_CONNECT
        valueFrom:
          configMapKeyRef:
            name: michael-env
            key: DB_URL
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10

